include: package:flutter_lints/flutter.yaml

linter:
  rules:
    # Errores críticos
    avoid_print: true
    avoid_annotating_with_dynamic: true
    
    # Estilo y rendimiento
    prefer_const_constructors: true
    prefer_single_quotes: true
    prefer_final_fields: true
    always_specify_types: true
    lines_longer_than_80_chars: true
    
    # Documentación (opcional pero recomendado)
    public_member_api_docs: false  # Desactivado temporalmente para reducir errores
    
    # Otros
    prefer_const_literals_to_create_immutables: true
    prefer_const_declarations: true
    prefer_final_locals: true
    avoid_unnecessary_containers: true
    sized_box_for_whitespace: true
    prefer_typing_uninitialized_variables: true
    prefer_expression_function_bodies: true
    prefer_int_literals: true
    sort_child_properties_last: true
    use_if_null_to_convert_nulls_to_bools: true
    unnecessary_lambdas: true
    unnecessary_to_list_in_spreads: true
    unawaited_futures: true
    library_private_types_in_public_api: true
    avoid_slow_async_io: true

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
  errors:
    invalid_annotation_target: ignore