name: wake_up_smile_and_learn
description: A children's app that helps kids wake up with a smile and learn.

publish_to: 'none'

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_form_builder: ^10.0.1
  shared_preferences: ^2.0.0
  animated_text_kit: ^4.2.1
  firebase_core: ^3.14.0
  firebase_auth: ^5.6.0
  cloud_firestore: ^5.6.9
  image_picker: ^1.0.5
  file_picker: ^10.2.0
  flutter_tts: ^4.2.3
  audioplayers: ^6.5.0
  flutter_local_notifications: ^17.0.0
  provider: ^6.1.1
  lottie: ^3.3.1
  flutter_svg: ^2.0.9
  google_fonts: any
  audio_session: ^0.2.2
  permission_handler: ^12.0.0+1
  path_provider: ^2.1.2
  sqflite: ^2.3.0
  intl: ^0.20.2
  flutter_animate: ^4.2.0
  confetti: ^0.8.0
  flutter_staggered_animations: ^1.1.1
  cached_network_image: ^3.3.0
  flutter_rating_bar: ^4.0.1
  flutter_sound: ^9.2.13
  vibration: ^3.1.3
  device_info_plus: ^11.5.0
  package_info_plus: ^8.3.0
  url_launcher: ^6.2.1
  flutter_native_splash: ^2.4.6
  flutter_launcher_icons: ^0.14.4
  timezone: ^0.9.2
  flutter_timezone: ^4.1.1
  screen_brightness_android: ^2.1.2
  receive_intent: ^0.2.5
  hive: ^2.2.3
  hive_flutter: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.8
  hive_generator: ^2.0.1
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/sounds/
    - assets/images/
    - assets/animations/
    - assets/avatars/
    - assets/music/
    - assets/themes/